messages:
  survival:
    already_in_world: "&cUž jsi ve survival světě!"
    teleport: "&aByl jsi teleportován! Hodně štěstí!"
  discord:
    join: "&6Připoj se na náš Discord: &9https://discord.gg/2huTdH2a23"
survival:
  worlds:
    - world
    - world_nether
    - world_the_end
spawn:
  world: "spawn"
  npc:
    survival: "cb86ae2e-17ac-41f2-9cb1-2706ce668ef8"
parkour:
  max_top: 5
  reward: 100
  location:
    start: 
      world: spawn
      x: 14.5
      y: 99.0
      z: -36.5
      yaw: 90.0
      pitch: 10.0
    finish:
      world: spawn
      x: 23.0
      y: 101.0
      z: -40.0
      yaw: 65.5
      pitch: 10.0
    hologram:
      x: 16.0
      y: 102.0
      z: -40.5
  region:
    pos1:
      x: 33.0
      y: 90.0
      z: -18.0
    pos2:
      x: -40.0
      y: 128.0
      z: -55.0
  npc:
    start: "830ce47a-7cfd-4877-860b-1e311cef6174"
    end: "a1002c35-3bdc-482a-a84e-ca35ade41b96"
  messages:
    join: "&aPřipojil jsi se do parkouru! Hodne štestí!"
    left: "&eOpustil jsi parkour!"
    fall: ""
    not_joined: "&cNejsi připojen do parkouru!"
    finished: "&aDokončil jsi parkour v čase &e{time}&a!"
    finished_others: "&6Hráč {player} &6dokončil parkour v čase &e{time}&6!"
    already: "&cUž jsi připojen!"
    actionbar: "&e&lČas: &6&l{time}"
    hologram_top: "&c#{n}. &e{username} &6{time}"